### ISSUE TITLE
Getting objective bound

### ISSUE THREAD

**Issue by CanLi1** [joehuchette/BARON.jl#13]
Hi,

I'm using BARON to solve a minimization problem. I wonder if there is a way to get the lower bound returned by BARON in JuMP. 

For CPLEX, we can use MathProgBase.getobjbound(m.internalModel). But it doesn't work for BARON. Is there any idea how to make this work?

Thanks!

Can

**Comment by joehuchette** [comment]
Please see if #14 works for you!

**Comment by r-gu** [comment]
Hi, I was trying to use getobjbound() as specified above to get the upper bound for a maximization problem but it keeps giving me the objective value instead of the best bound. I am using BARON version 19.7.13 and BARON.jl version 0.4.4. Can this be a bug? Thanks.
-RG

**Comment by joehuchette** [comment]
@r-gu The behavior you describe would be considered a bug.

**Comment by r-gu** [comment]
Yes, I figured that Baron always assigns the lower bound value to
getobjbound(). So, converting the maximization problem to a minimization
problem solved the issue. Thanks.

-RG

**Comment by joehuchette** [comment]
I consider this behavior a bug; it is fixed in the latest version.
