### ISSUE TITLE
Error with equality constraints

### ISSUE THREAD

**Issue by tasseff** [joehuchette/BARON.jl#21]
This appears to be due to a change in this commit: https://github.com/joehuchette/BARON.jl/commit/3d325c311eb379f21da3f66ed9ab3cd888c0a783

Writing out the `.bar` file with equality constraints results in equality symbols being wrapped with parentheses, i.e., `(==)`. This appears to be incorrect syntax for a `.bar` file. When `(==)` is replaced with `==` in the `.bar` file, it can be run by the BARON executable correctly.

Here's an example that should result in an error:

```julia
using BARON
using JuMP

model = Model()
@variable(model, x, start = 0.0)
@variable(model, y, start = 0.0)
@constraint(model, x + y == 10)
baron = BaronSolver(LPSol = 3, CplexLibName = "libcplex1280.so")
@NLobjective(model, Min, (1 - x)^2 + 100(y - x^2)^2)
setsolver(model, baron)
solve(model)
```

**Comment by joehuchette** [comment]
Thanks for catching my (careless) error! I've pushed a fix (37964c1f120a572a55c67c4bb354f289acef44bb) and have a new patch release in the pipeline (https://github.com/JuliaLang/METADATA.jl/pull/18816).
