### ISSUE TITLE
Error in Baron.jl

### ISSUE THREAD

**Issue by harshangrjn** [joehuchette/BARON.jl#25]
I am trying to run this NLP: 
```
m = Model(solver=BaronSolver())
ub = [6,4]
@variable(m, 0 ≤ x[i=1:2] ≤ ub[i])
@NLconstraint(m, x[1]*x[2] ≤ 4)
@NLobjective(m, Min, -x[1] - x[2])
solve(m)
```
But getting this error: 
```ERROR: MethodError: no method matching push!(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Tuple{Symbol,String})```

Has this been fixed earlier? 
Thanks!

**Comment by harshangrjn** [comment]
Info: Using BARON v0.4.3 and JuMP v0.18.5

**Comment by joehuchette** [comment]
Thanks for the report! Should be fixed in c3fb500d9211acbf11de58a7c1404f4b24f1d846.

**Comment by joehuchette** [comment]
Bump this issue if it does indeed fix it for you, and I'll push a patch release.

**Comment by harshangrjn** [comment]
@joehuchette Thanks for fixing this. It works now. Go ahead with the patch release.
