### ISSUE TITLE
Plans for JuMP 0.19 interop?

### ISSUE THREAD

**Issue by tkoolen** [joehuchette/BARON.jl#26]
Hey @joehuchette. I was just wondering what your plans are for supporting JuMP 0.19. I guess there are (at least) two possible avenues:

* full rewrite using MOI. SCIP went this route.
* wrap the existing MPB interface, similar to AmplNLWriter.

Any thoughts?

**Comment by joehuchette** [comment]
I was planning to bite the bullet and update to MOI: the surface area of the package isn't too large, and it mostly uses the nonlinear interface which is largely unchanged. This is one of the projects I was hoping to tackle at the JuMP-dev workshop this week :)

**Comment by tkoolen** [comment]
Wow, that would be awesome, thank you!

**Comment by rcallen24** [comment]
@joehuchette 

If this issue is still open after Christmas, I would be willing to contribute to the merge.

**Comment by tkoolen** [comment]
I feel #31 is probably about 80 - 90% of the way to full functionality. What's missing is handling of `NLPBlock`s, but that hasn't changed much from MathProgBase so it shouldn't be that difficult to reimplement. I just didn't do it because I didn't personally need it and my time is limited right now.

**Comment by pedroborgesmelo** [comment]
Hello guys!

The tests gear.jl and minlp.jl are not running on my computer.. it says 

" ... Attribute MathOptInterface.NLPBlock() is not supported by the model."

Somebody knows how to make it work?

Tks.

**Comment by joehuchette** [comment]
The newest version of BARON.jl only supports quadratically constrained problems (for now). It was partially updated for the new communication layer used by JuMP ([MathOptInterface](https://github.com/JuliaOpt/MathOptInterface.jl)). I'm planning to get around to finishing the job in the coming weeks.
