### ISSUE TITLE
Max runtimes

### ISSUE THREAD

**Issue by harshangrjn** [joehuchette/BARON.jl#29]
Baron seems to apply 500s time limit by default on larger NLPs. Couldn't locate where this limit was chosen in Baron.jl. Also I do not have sum.lst file in the Baron's folder, where these user-defined parameters can be entered. So, was wondering if is this to do with Baron's default solver options or is Baron.jl applying this time limit while creating the .bar file?

**Comment by joehuchette** [comment]
We shouldn't be setting a time limit by default from BARON.jl. Looking at the [BARON manual](https://minlp.com/downloads/docs/baron%20manual.pdf), there appears to be a MaxTime parameter that defaults to 1000 seconds, so you could try changing that.

Feel free to reopen if there's something actionable at the julia level.

**Comment by harshangrjn** [comment]
@joehuchette Thanks! MaxTime parameter works. I was just wondering where the 500s default limit was getting applied to Baron in the Julia level.

**Comment by joehuchette** [comment]
Agreed that the 500 is unexpected, I’d guess maybe it’s either 1) you’re using an older version of BARON and they’ve since changed the default, or 2) they use a different (shorter) time limit for subproblems.

**Comment by harshangrjn** [comment]
@joehuchette Its probably (2) as I have the most recent version of Baron. Good that 'MaxTime' addresses the issue. Thanks!
