### ISSUE TITLE
Optimizer not defined

### ISSUE THREAD

**Issue by cguzmanr** [joehuchette/BARON.jl#33]
Hi there
I am just testing one of the examples attached to this repository and it throws out: 

UndefVarError: Optimizer not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\Base.jl:13
 [2] top-level scope at In[33]:9

I am using Baron v0.4.4 and MathProgBase v0.7.8
Have you any idea why is happening above when calling Baron?
Thanks!

**Comment by joehuchette** [comment]
Which one?

**Comment by cguzmanr** [comment]
Gear

**Comment by joehuchette** [comment]
I can't recreate this error, but note that BARON v0.4.4 does not support general nonlinear problems like gear. We are in the process of porting the library over to the new [MathOptInterface](https://github.com/JuliaOpt/MathOptInterface.jl) standard, and I'm hoping this will be complete in the coming weeks.

**Comment by cguzmanr** [comment]
ok. Thanks much for your help.
