### ISSUE TITLE
MPS file

### ISSUE THREAD

**Issue by cguzmanr** [joehuchette/BARON.jl#34]
Hi there
Do you have an example showing how to use BARON from Julia for a problem on MPS format?
Thanks!

**Comment by joehuchette** [comment]
If you're starting with a JuMP model, you can use [JuMP.write_to_file](http://www.juliaopt.org/JuMP.jl/dev/solvers/#JuMP.write_to_file).

Closing since this is a usability question best asked on the [discourse](https://discourse.julialang.org/c/domain/opt).
