### ISSUE TITLE
Unrecognized abs(x)

### ISSUE THREAD

**Issue by harshangrjn** [joehuchette/BARON.jl#38]
v0.6.1: This issue may have appeared before but I get `ERROR: LoadError: UnrecognizedExpressionException: unrecognized comparison expression: abs(x[1])` when there is an abs(x) in a constraint or in the objective. I see a TODO line for |x| and x^y here https://github.com/joehuchette/BARON.jl/blob/db6ffe102e988b592138698d880a8744d6b09f6b/src/util.jl#L64  

Just wanted to make sure this was reported in case will be fixed later. Thanks!

**Comment by joehuchette** [comment]
BARON doesn't natively support either ``abs`` or ``x^y``. In the documentation, they suggest transformations of ``abs(x) = sqrt(x^2)`` and ``x^y = exp(y * log(x))``. Apparently AMPL, GAMS, etc. do these transformations automatically, and we could do the same here.

Also, the error message you receive should be more informative.

I'll try to take a look at both in the next week or so.

**Comment by harshangrjn** [comment]
Thanks @joehuchette! I kind of did this transformation myself but was curious how AMPL/GAMS was handling this. An error message explicitly asking for the user to transform should be sufficient.
