### ISSUE TITLE
If you forget the environmental variable at first `using` time, it's hard to fix

### ISSUE THREAD

**Issue by ericphanson** [joehuchette/BARON.jl#39]
In theses lines 

https://github.com/joehuchette/BARON.jl/blob/1188123f830b83017f3757f5f0ffde5ce59a81fc/src/BARON.jl#L5-L9

`baron_exec` gets precompiled in, but if you forgot to set the environmental variable before the first run, you are sort of out of luck (you need to get BARON.jl to re-precompile, which I'm not really sure how to do). 

One fix would be to instead use a `build/deps.jl` file, which does the ENV check and writes the `const baron_exec = ...` out to a file `build/path.jl` or whatever, and then `src/BARON.jl` just does an `include(joinpath(@__DIR__, "..", "build", "path.jl"))` to get the path loaded in. That way you only need the environmental variable at build time, which you can retrigger by `Pkg.build("BARON")`.

Another way to add flexibility would be to make `const baron_exec = Ref("...")` so then the user could do `BARON.baron_exec[] = "newpath"` to fix the path at runtime if needed.

**Comment by ericphanson** [comment]
Doing
```
@eval BARON begin
       const baron_exec = ENV["BARON_EXEC"]
end
```
seems to work around it okay, but I think it's a bit dangerous because there's no guarantee that if you redefine the constant like that that functions which have already been compiled with the old constant will pick up the new value.

**Comment by joehuchette** [comment]
Thanks for reporting. The ``build/deps.jl`` approach you describe is the best way to handle this IMO--you really should only need the environment variable set at build time. If you're interested in creating a PR that would be very welcome.
