### ISSUE TITLE
ERROR: can’t open nl file

### ISSUE THREAD

**Issue by jiawei92** [joehuchette/BARON.jl#46]
I was trying to use BARON to solve some problems.

JuMP.jl version: 0.21.5
BARON.jl version: 0.6.5

When I run my program, the following error occurs:

```
C:\Program Files\ampl_mswin64\baron.exe: can't open C:\Users\Lujia\AppData\Local\Temp\jl_1V2Lgu\baron_problem.bar.nl
ERROR: LoadError: failed process: Process(`'C:\Program Files\ampl_mswin64\baron.exe' 'C:\Users\Lujia\AppData\Local\Temp\jl_1V2Lgu\baron_problem.bar'`, ProcessExited(1)) [1]
```

It seems the baron executable cannot find a .nl file. How can I solve that issue?

I do see C:\Users\Lujia\AppData\Local\Temp\jl_1V2Lgu\baron_problem.bar exists when using debug mode.

**Comment by joehuchette** [comment]
Can you verify that running BARON from the shell outside of Julia works as expected?

The error is a bit odd though. I'm not sure where the ``.nl`` extension is coming from; maybe it's something internal to BARON. As a test, you could try setting the problem file name manually, using the ``"ProName"`` option passed to ``BARON.Optimizer``

**Comment by jiawei92** [comment]
> Can you verify that running BARON from the shell outside of Julia works as expected?
> 
> The error is a bit odd though. I'm not sure where the `.nl` extension is coming from; maybe it's something internal to BARON. As a test, you could try setting the problem file name manually, using the `"ProName"` option passed to `BARON.Optimizer`

If I pass the `.bar` file to baron.exe in the shell, the error still exists.
![image](https://user-images.githubusercontent.com/40050673/96189423-4e65c180-0ef5-11eb-8660-c81ce1d0047d.png)

**Comment by joehuchette** [comment]
If you can reproduce this outside of Julia, then this is an issue to raise with BARON directly. It seems like there's something off with BARON and how it interacts with your file system, but I'm only speculating.
