### ISSUE TITLE
Errors related to solve_farkas on package testing

### ISSUE THREAD

**Issue by trathi05** [joehuchette/BARON.jl#48]
I just downloaded `BARON.jl` on my machine and ran the command `test BARON`:

```
Test Summary:                         | Pass  Error  Total
Unit                                  |   94     16    110
  solve_qcp_edge_cases                |   14            14
  solve_farkas_interval_lower         |    1      2      3
  add_variable                        |    3             3
  solve_singlevariable_obj            |    8             8
  solve_unbounded_model               |    1             1
  solve_constant_obj                  |    8             8
  solve_single_variable_dual_max      |              No tests
  solve_single_variable_dual_min      |              No tests
  solver_name                         |    1             1
  solve_time                          |    6             6
  solve_duplicate_terms_obj           |    8             8
  add_variables                       |    3             3
  feasibility_sense                   |    3             3
  solve_farkas_lessthan               |    1      2      3
  max_sense                           |    3             3
  solve_farkas_interval_upper         |    1      2      3
  solve_qp_zero_offdiag               |    7             7
  variablenames                       |    5             5
  solve_farkas_greaterthan            |    1      2      3
  min_sense                           |    3             3
  solve_twice                         |              No tests
  solve_farkas_variable_lessthan_max  |    1      2      3
  solve_duplicate_terms_scalar_affine |    6             6
  solve_farkas_variable_lessthan      |    1      2      3
  solve_farkas_equalto_upper          |    1      2      3
  getvariable                         |    2             2
  get_objective_function              |    5             5
  solve_farkas_equalto_lower          |    1      2      3
```

I have CPLEX 20.1 and BARON (2019.12.07) installed and running Julia 1.6.1.

Following are the packages installed:
```
BARON v0.6.5
CPLEX v0.7.7
Gurobi v0.9.12
Ipopt v0.6.5
JuMP v0.21.8
```

I am not able to understand why so many tests are failing. Is it due to compatibility issues of the packages or is there some other reason? Thanks.

**Comment by odow** [comment]
BARON.jl works, but it hasn't been updated to the latest version of MathOptInterface so it may fail some tests. 

You can safely ignore them for general usage.

**Comment by trathi05** [comment]
Okay. Another thing I noticed is that `BARON.jl` doesn't recognize the current version of CPLEX, i.e., CPLEX 20.1, and switch to the CLP solver.

The message it displays during the run looks like this:
```
 Unable to find/load CPLEX library cplex12100.dll.
 Unable to find/load CPLEX library cplex1290.dll.
 Changing option LPSol to 8 (CLP) and continuing.
```

 Is it also just because the package is not updated and can work only with CPLEX 12.9/12.10?

**Comment by odow** [comment]
This isn't coming from BARON.jl. You should contact the Optimization Firm for support. Although presumably the version of BARON you have isn't compatible with CPLEX 20.1.

**Comment by trathi05** [comment]
Yes, that totally makes sense. I am using an old version of BARON since I have not updated my license yet.
Thanks for clearing this point.

I will close this issue for now. I may open it in the future if I encounter some other problems with `BARON.jl` and `MathOptInterface` incompatibility.

Thanks again for the quick responses.
