### ISSUE TITLE
Problem linking to Baron

### ISSUE THREAD

**Issue by mckeeta** [joehuchette/BARON.jl#5]
Hello,

I have downloaded the Baron executables from their website and put the license file in the same directory. 
![directory](https://user-images.githubusercontent.com/28026327/29998055-f1d04266-8fd5-11e7-8373-dcd4f37a617e.png)

I then added the environment variable pointing to that directory:

![environmentvariable](https://user-images.githubusercontent.com/28026327/29998065-44595cca-8fd6-11e7-831e-9ce5744810bc.png)

I wrote a simple code 
![code](https://user-images.githubusercontent.com/28026327/29998071-793cd3ae-8fd6-11e7-9467-3eeda7319a5e.png)

I tried running it but ran into this problem 
![terminalpic](https://user-images.githubusercontent.com/28026327/29998075-88fb9320-8fd6-11e7-9e98-8099c6e712ad.png)

It seems that JuMP can't find the file it needs. Can you please help me with this matter?

Thanks a lot,
Moe

**Comment by bbrunaud** [comment]
The `BARON_EXEC` variable must point exactly to the executable file, not just the path.

``
export BARON_EXEC=/home/mckeeta/Downloads/baron-lin64/baron
``

**Comment by mckeeta** [comment]
Thanks for the quick reply. I tried to make the change, unfortunately the problem persists.

![envar2](https://user-images.githubusercontent.com/28026327/29999469-0f55b0c2-8fff-11e7-90dd-fe1825765295.png)

![terminal2](https://user-images.githubusercontent.com/28026327/29999470-15b80a96-8fff-11e7-8dd2-a969b672892c.png)

**Comment by bbrunaud** [comment]
Post the output of `echo $BARON_EXEC`
Also check that `/tmp/baron_problem.bar` exists after running the code

**Comment by mckeeta** [comment]
Do you mean show you the output or does post mean something else?

![echo](https://user-images.githubusercontent.com/28026327/30000462-b43c18ac-9021-11e7-8ea6-d44fb255dc54.png)

also /tmp/baron_problem.bar exists but not inside the directory /home/mckeeta/Downloads/baron-lin64

it's outside my home directory all together. should I A) copy it into the directory (I'm worried in that case it will not update in the correct spot if it updates at all) or B) remove the environment variable link and make it seek baron_problem.bar directly from /tmp/ (should I in that case move all of the files from my directory to tmp)?

![tmp](https://user-images.githubusercontent.com/28026327/30000476-6f92d640-9022-11e7-897a-875e2e5e4245.png)

Thanks a bunch

**Comment by bbrunaud** [comment]
I think your variable definition should be
``
export BARON_EXEC=/home/mckeeta/Downloads/baron-lin64/baron
``
and not
``
export BARON_EXEC='/home/mckeeta/Downloads/baron-lin64/baron':$BARON_EXEC
``
when you do `echo $BARON_EXEC ` the last semicolon shouldn't be there.

**Comment by mckeeta** [comment]
Thanks! That did the trick.

**Comment by mckeeta** [comment]
If I may trouble you with one last thing, it seems that I'm in demo mode which is very limited. How do I link my license? I have received a text file from baron with my information inside it and a license number. I simply copy pasted it into /home/mckeeta/Downloads/baron-lin64/ 
you can see a snap of the file up in this thread with the name baronlice.txt

I tried reading the src code for clues and looked around in the .julia directory in hopes that I code hardwire it somewhere but I was without luck.

![baronlicense](https://user-images.githubusercontent.com/28026327/30037528-699053fe-9170-11e7-8d8d-aa654e6f57cc.png)
